#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Scrapper")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertCustomer(Customer instance);
  partial void UpdateCustomer(Customer instance);
  partial void DeleteCustomer(Customer instance);
  partial void InsertPickup(Pickup instance);
  partial void UpdatePickup(Pickup instance);
  partial void DeletePickup(Pickup instance);
  partial void InsertScrap(Scrap instance);
  partial void UpdateScrap(Scrap instance);
  partial void DeleteScrap(Scrap instance);
  partial void InsertEmployee(Employee instance);
  partial void UpdateEmployee(Employee instance);
  partial void DeleteEmployee(Employee instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ScrapperConnectionString1"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Customer> Customers
	{
		get
		{
			return this.GetTable<Customer>();
		}
	}
	
	public System.Data.Linq.Table<Pickup> Pickups
	{
		get
		{
			return this.GetTable<Pickup>();
		}
	}
	
	public System.Data.Linq.Table<Schedule> Schedules
	{
		get
		{
			return this.GetTable<Schedule>();
		}
	}
	
	public System.Data.Linq.Table<Buy> Buys
	{
		get
		{
			return this.GetTable<Buy>();
		}
	}
	
	public System.Data.Linq.Table<Supply> Supplies
	{
		get
		{
			return this.GetTable<Supply>();
		}
	}
	
	public System.Data.Linq.Table<Scrap> Scraps
	{
		get
		{
			return this.GetTable<Scrap>();
		}
	}
	
	public System.Data.Linq.Table<Employee> Employees
	{
		get
		{
			return this.GetTable<Employee>();
		}
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Customer")]
	public int SP_Customer([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ACTION", DbType="Int")] System.Nullable<int> aCTION, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string cname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string caddress, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string ccontact, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string ctype, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string cpassword)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), aCTION, cid, cname, caddress, ccontact, ctype, cpassword);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Pickup")]
	public int SP_Pickup([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ACTION", DbType="Int")] System.Nullable<int> aCTION, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> slot_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string status_, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string start_time, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string end_time)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), aCTION, slot_id, status_, start_time, end_time);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Schedule")]
	public int SP_Schedule([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ACTION", DbType="Int")] System.Nullable<int> aCTION, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> sdate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> slot_id)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), aCTION, cid, sdate, slot_id);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Scrap")]
	public int SP_Scrap([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ACTION", DbType="Int")] System.Nullable<int> aCTION, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string material_type, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Real")] System.Nullable<float> buying_price, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Real")] System.Nullable<float> selling_price)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), aCTION, material_type, buying_price, selling_price);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Buys")]
	public int SP_Buys([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ACTION", DbType="Int")] System.Nullable<int> aCTION, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> date_of_purchase, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> scrapid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> bweight)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), aCTION, cid, date_of_purchase, scrapid, bweight);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Supplies")]
	public int SP_Supplies([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ACTION", DbType="Int")] System.Nullable<int> aCTION, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> date_of_supply, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> scrapid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> sweight)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), aCTION, cid, date_of_supply, scrapid, sweight);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Employee")]
	public int SP_Employee([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ACTION", DbType="Int")] System.Nullable<int> aCTION, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> eid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string ename, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string eaddress, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string econtact, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Real")] System.Nullable<float> salary, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string designation, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(40)")] string gender, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string area_name)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), aCTION, eid, ename, eaddress, econtact, password, salary, designation, gender, area_name);
		return ((int)(result.ReturnValue));
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Customer")]
public partial class Customer : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _cid;
	
	private string _cname;
	
	private string _caddress;
	
	private string _ccontact;
	
	private string _ctype;
	
	private string _cpassword;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncidChanging(int value);
    partial void OncidChanged();
    partial void OncnameChanging(string value);
    partial void OncnameChanged();
    partial void OncaddressChanging(string value);
    partial void OncaddressChanged();
    partial void OnccontactChanging(string value);
    partial void OnccontactChanged();
    partial void OnctypeChanging(string value);
    partial void OnctypeChanged();
    partial void OncpasswordChanging(string value);
    partial void OncpasswordChanged();
    #endregion
	
	public Customer()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int cid
	{
		get
		{
			return this._cid;
		}
		set
		{
			if ((this._cid != value))
			{
				this.OncidChanging(value);
				this.SendPropertyChanging();
				this._cid = value;
				this.SendPropertyChanged("cid");
				this.OncidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cname", DbType="VarChar(100)")]
	public string cname
	{
		get
		{
			return this._cname;
		}
		set
		{
			if ((this._cname != value))
			{
				this.OncnameChanging(value);
				this.SendPropertyChanging();
				this._cname = value;
				this.SendPropertyChanged("cname");
				this.OncnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_caddress", DbType="VarChar(255)")]
	public string caddress
	{
		get
		{
			return this._caddress;
		}
		set
		{
			if ((this._caddress != value))
			{
				this.OncaddressChanging(value);
				this.SendPropertyChanging();
				this._caddress = value;
				this.SendPropertyChanged("caddress");
				this.OncaddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ccontact", DbType="VarChar(20)")]
	public string ccontact
	{
		get
		{
			return this._ccontact;
		}
		set
		{
			if ((this._ccontact != value))
			{
				this.OnccontactChanging(value);
				this.SendPropertyChanging();
				this._ccontact = value;
				this.SendPropertyChanged("ccontact");
				this.OnccontactChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ctype", DbType="VarChar(100)")]
	public string ctype
	{
		get
		{
			return this._ctype;
		}
		set
		{
			if ((this._ctype != value))
			{
				this.OnctypeChanging(value);
				this.SendPropertyChanging();
				this._ctype = value;
				this.SendPropertyChanged("ctype");
				this.OnctypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cpassword", DbType="VarChar(50)")]
	public string cpassword
	{
		get
		{
			return this._cpassword;
		}
		set
		{
			if ((this._cpassword != value))
			{
				this.OncpasswordChanging(value);
				this.SendPropertyChanging();
				this._cpassword = value;
				this.SendPropertyChanged("cpassword");
				this.OncpasswordChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pickup")]
public partial class Pickup : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _slot_id;
	
	private string _status_;
	
	private string _start_time;
	
	private string _end_time;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onslot_idChanging(int value);
    partial void Onslot_idChanged();
    partial void Onstatus_Changing(string value);
    partial void Onstatus_Changed();
    partial void Onstart_timeChanging(string value);
    partial void Onstart_timeChanged();
    partial void Onend_timeChanging(string value);
    partial void Onend_timeChanged();
    #endregion
	
	public Pickup()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_slot_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int slot_id
	{
		get
		{
			return this._slot_id;
		}
		set
		{
			if ((this._slot_id != value))
			{
				this.Onslot_idChanging(value);
				this.SendPropertyChanging();
				this._slot_id = value;
				this.SendPropertyChanged("slot_id");
				this.Onslot_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status_", DbType="VarChar(100)")]
	public string status_
	{
		get
		{
			return this._status_;
		}
		set
		{
			if ((this._status_ != value))
			{
				this.Onstatus_Changing(value);
				this.SendPropertyChanging();
				this._status_ = value;
				this.SendPropertyChanged("status_");
				this.Onstatus_Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_start_time", DbType="VarChar(255)")]
	public string start_time
	{
		get
		{
			return this._start_time;
		}
		set
		{
			if ((this._start_time != value))
			{
				this.Onstart_timeChanging(value);
				this.SendPropertyChanging();
				this._start_time = value;
				this.SendPropertyChanged("start_time");
				this.Onstart_timeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_end_time", DbType="VarChar(20)")]
	public string end_time
	{
		get
		{
			return this._end_time;
		}
		set
		{
			if ((this._end_time != value))
			{
				this.Onend_timeChanging(value);
				this.SendPropertyChanging();
				this._end_time = value;
				this.SendPropertyChanged("end_time");
				this.Onend_timeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Schedule")]
public partial class Schedule
{
	
	private System.Nullable<int> _cid;
	
	private System.Nullable<System.DateTime> _sdate;
	
	private System.Nullable<int> _slot_id;
	
	public Schedule()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cid", DbType="Int")]
	public System.Nullable<int> cid
	{
		get
		{
			return this._cid;
		}
		set
		{
			if ((this._cid != value))
			{
				this._cid = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdate", DbType="Date")]
	public System.Nullable<System.DateTime> sdate
	{
		get
		{
			return this._sdate;
		}
		set
		{
			if ((this._sdate != value))
			{
				this._sdate = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_slot_id", DbType="Int")]
	public System.Nullable<int> slot_id
	{
		get
		{
			return this._slot_id;
		}
		set
		{
			if ((this._slot_id != value))
			{
				this._slot_id = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Buys")]
public partial class Buy
{
	
	private System.Nullable<int> _cid;
	
	private System.Nullable<System.DateTime> _date_of_purchase;
	
	private System.Nullable<int> _scrapid;
	
	private System.Nullable<double> _bweight;
	
	public Buy()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cid", DbType="Int")]
	public System.Nullable<int> cid
	{
		get
		{
			return this._cid;
		}
		set
		{
			if ((this._cid != value))
			{
				this._cid = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_of_purchase", DbType="Date")]
	public System.Nullable<System.DateTime> date_of_purchase
	{
		get
		{
			return this._date_of_purchase;
		}
		set
		{
			if ((this._date_of_purchase != value))
			{
				this._date_of_purchase = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scrapid", DbType="Int")]
	public System.Nullable<int> scrapid
	{
		get
		{
			return this._scrapid;
		}
		set
		{
			if ((this._scrapid != value))
			{
				this._scrapid = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bweight", DbType="Float")]
	public System.Nullable<double> bweight
	{
		get
		{
			return this._bweight;
		}
		set
		{
			if ((this._bweight != value))
			{
				this._bweight = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Supplies")]
public partial class Supply
{
	
	private System.Nullable<int> _cid;
	
	private System.Nullable<System.DateTime> _date_of_supply;
	
	private System.Nullable<int> _scrapid;
	
	private System.Nullable<double> _sweight;
	
	public Supply()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cid", DbType="Int")]
	public System.Nullable<int> cid
	{
		get
		{
			return this._cid;
		}
		set
		{
			if ((this._cid != value))
			{
				this._cid = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_of_supply", DbType="Date")]
	public System.Nullable<System.DateTime> date_of_supply
	{
		get
		{
			return this._date_of_supply;
		}
		set
		{
			if ((this._date_of_supply != value))
			{
				this._date_of_supply = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scrapid", DbType="Int")]
	public System.Nullable<int> scrapid
	{
		get
		{
			return this._scrapid;
		}
		set
		{
			if ((this._scrapid != value))
			{
				this._scrapid = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sweight", DbType="Float")]
	public System.Nullable<double> sweight
	{
		get
		{
			return this._sweight;
		}
		set
		{
			if ((this._sweight != value))
			{
				this._sweight = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Scrap")]
public partial class Scrap : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _scrapid;
	
	private string _material_type;
	
	private System.Nullable<float> _buying_price;
	
	private System.Nullable<float> _selling_price;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnscrapidChanging(int value);
    partial void OnscrapidChanged();
    partial void Onmaterial_typeChanging(string value);
    partial void Onmaterial_typeChanged();
    partial void Onbuying_priceChanging(System.Nullable<float> value);
    partial void Onbuying_priceChanged();
    partial void Onselling_priceChanging(System.Nullable<float> value);
    partial void Onselling_priceChanged();
    #endregion
	
	public Scrap()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scrapid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int scrapid
	{
		get
		{
			return this._scrapid;
		}
		set
		{
			if ((this._scrapid != value))
			{
				this.OnscrapidChanging(value);
				this.SendPropertyChanging();
				this._scrapid = value;
				this.SendPropertyChanged("scrapid");
				this.OnscrapidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_material_type", DbType="VarChar(100)")]
	public string material_type
	{
		get
		{
			return this._material_type;
		}
		set
		{
			if ((this._material_type != value))
			{
				this.Onmaterial_typeChanging(value);
				this.SendPropertyChanging();
				this._material_type = value;
				this.SendPropertyChanged("material_type");
				this.Onmaterial_typeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_buying_price", DbType="Real")]
	public System.Nullable<float> buying_price
	{
		get
		{
			return this._buying_price;
		}
		set
		{
			if ((this._buying_price != value))
			{
				this.Onbuying_priceChanging(value);
				this.SendPropertyChanging();
				this._buying_price = value;
				this.SendPropertyChanged("buying_price");
				this.Onbuying_priceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_selling_price", DbType="Real")]
	public System.Nullable<float> selling_price
	{
		get
		{
			return this._selling_price;
		}
		set
		{
			if ((this._selling_price != value))
			{
				this.Onselling_priceChanging(value);
				this.SendPropertyChanging();
				this._selling_price = value;
				this.SendPropertyChanged("selling_price");
				this.Onselling_priceChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Employee")]
public partial class Employee : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _eid;
	
	private string _ename;
	
	private string _eaddress;
	
	private string _econtact;
	
	private System.Nullable<System.DateTime> _DOB;
	
	private System.Nullable<float> _salary;
	
	private string _designation;
	
	private string _gender;
	
	private string _area_name;
	
	private string _password_;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OneidChanging(int value);
    partial void OneidChanged();
    partial void OnenameChanging(string value);
    partial void OnenameChanged();
    partial void OneaddressChanging(string value);
    partial void OneaddressChanged();
    partial void OnecontactChanging(string value);
    partial void OnecontactChanged();
    partial void OnDOBChanging(System.Nullable<System.DateTime> value);
    partial void OnDOBChanged();
    partial void OnsalaryChanging(System.Nullable<float> value);
    partial void OnsalaryChanged();
    partial void OndesignationChanging(string value);
    partial void OndesignationChanged();
    partial void OngenderChanging(string value);
    partial void OngenderChanged();
    partial void Onarea_nameChanging(string value);
    partial void Onarea_nameChanged();
    partial void Onpassword_Changing(string value);
    partial void Onpassword_Changed();
    #endregion
	
	public Employee()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int eid
	{
		get
		{
			return this._eid;
		}
		set
		{
			if ((this._eid != value))
			{
				this.OneidChanging(value);
				this.SendPropertyChanging();
				this._eid = value;
				this.SendPropertyChanged("eid");
				this.OneidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ename", DbType="VarChar(100)")]
	public string ename
	{
		get
		{
			return this._ename;
		}
		set
		{
			if ((this._ename != value))
			{
				this.OnenameChanging(value);
				this.SendPropertyChanging();
				this._ename = value;
				this.SendPropertyChanged("ename");
				this.OnenameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eaddress", DbType="VarChar(255)")]
	public string eaddress
	{
		get
		{
			return this._eaddress;
		}
		set
		{
			if ((this._eaddress != value))
			{
				this.OneaddressChanging(value);
				this.SendPropertyChanging();
				this._eaddress = value;
				this.SendPropertyChanged("eaddress");
				this.OneaddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_econtact", DbType="VarChar(20)")]
	public string econtact
	{
		get
		{
			return this._econtact;
		}
		set
		{
			if ((this._econtact != value))
			{
				this.OnecontactChanging(value);
				this.SendPropertyChanging();
				this._econtact = value;
				this.SendPropertyChanged("econtact");
				this.OnecontactChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="Date")]
	public System.Nullable<System.DateTime> DOB
	{
		get
		{
			return this._DOB;
		}
		set
		{
			if ((this._DOB != value))
			{
				this.OnDOBChanging(value);
				this.SendPropertyChanging();
				this._DOB = value;
				this.SendPropertyChanged("DOB");
				this.OnDOBChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salary", DbType="Real")]
	public System.Nullable<float> salary
	{
		get
		{
			return this._salary;
		}
		set
		{
			if ((this._salary != value))
			{
				this.OnsalaryChanging(value);
				this.SendPropertyChanging();
				this._salary = value;
				this.SendPropertyChanged("salary");
				this.OnsalaryChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_designation", DbType="VarChar(100)")]
	public string designation
	{
		get
		{
			return this._designation;
		}
		set
		{
			if ((this._designation != value))
			{
				this.OndesignationChanging(value);
				this.SendPropertyChanging();
				this._designation = value;
				this.SendPropertyChanged("designation");
				this.OndesignationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="VarChar(40)")]
	public string gender
	{
		get
		{
			return this._gender;
		}
		set
		{
			if ((this._gender != value))
			{
				this.OngenderChanging(value);
				this.SendPropertyChanging();
				this._gender = value;
				this.SendPropertyChanged("gender");
				this.OngenderChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_area_name", DbType="VarChar(50)")]
	public string area_name
	{
		get
		{
			return this._area_name;
		}
		set
		{
			if ((this._area_name != value))
			{
				this.Onarea_nameChanging(value);
				this.SendPropertyChanging();
				this._area_name = value;
				this.SendPropertyChanged("area_name");
				this.Onarea_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password_", DbType="VarChar(50)")]
	public string password_
	{
		get
		{
			return this._password_;
		}
		set
		{
			if ((this._password_ != value))
			{
				this.Onpassword_Changing(value);
				this.SendPropertyChanging();
				this._password_ = value;
				this.SendPropertyChanged("password_");
				this.Onpassword_Changed();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
